### PR TITLE
Feature/synthesis

### PR DESCRIPTION
**Pull request by yanicasa**
Update readme regarding synthesis thinks
Add ability to uses multiples lib files
Add generic constraints -> reduce drastically max frequency (dedicated commit)

### CODE REVIEW

**Review by JeanRochCoulon — APPROVED** [review]

**Review by JeanRochCoulon — CHANGES_REQUESTED** [review]
Yannick, as discussed I would be pleased to merge all the modifications except the clock one. Could you remove the clock modification from your PR (Et la garder au chaud pour une prochaine PR) ?   Because I did not find a way to merge only a part of your modifications.

**Comment by yanicasa** [comment]
I rewrite the PR, one commit only, contraints included but disabled by default

**Review by JeanRochCoulon — APPROVED** [review]

**Comment by JeanRochCoulon** [comment]
Yannick,    Tu as un souci de eclipsefdn/eca. Du coup je ne peux pas merger tes modifications.  Il faut corriger

**Comment by yanicasa** [comment]
Je pensais que c'etait deja fait.. j'ai valider sur eclipse, tu dois pouvoir relancer le job

**Pull request closed without merging**
